### PR TITLE
`LLM`: Add llm subsystem

### PR DESCRIPTION
**Pull request by Hialus**
Very rough draft for early review

# Motivation
For Pyris V2 we need a robust and extendable subsystem for handling LLMs. This system will support different LLM selection strategies in the future, which are all accessible through the same Interface.
 
# Description
Class Diagram:
ClassDiagram

Explanation:
- The `RequestHandlerInterface` is the entrypoint / Facade for the entire subsystem
- The `BasicRequestHandler` is the first simple implementation of it, which simply forwards to one specified LLM
- In the future different request handlers would implement different logic for switching between multiple LLMs
- An `IrisMessage` is our own message format, which we can then convert to/from e.g. Langchain messages
    - Currently only has `role` and `text`, but in the near future also supports images and possibly more
- The `LlmManager` is a singleton, which stores/handles all the different LLMs
- The different `LlmWrapperInterface`s and their implementations are the direct connection to the LLMs and handle any vendor specific logic (i.e. converting messages)

There is also the follow up #52 to improve the config file parsing

### CODE REVIEW

**Review by kaancayli — APPROVED** [review]
Looks good to me. LGTM

**Comment by yassinsws** [comment]
Can we change the model in Basic request Handler from str to Enum?

**Comment by Hialus** [comment]
> For Futur's work, maybe change the model to enum

This is not possible, as it is an identifier from a config fille. The model identifier is therefore dynamic

**Review by yassinsws — APPROVED** [review]
Looks good to me for a first Version, approved !

**Pull request merged**
